swagger: '2.0'
info:
  title: ChannelShipper & Royal Mail Public Labels Manifests API
  description: Import your orders, retrieve your orders and generate labels.
  version: 1.0.0
basePath: /api/v1
consumes:
- application/json
produces:
- application/json
tags:
- name: Manifests
paths:
  /manifests:
    post:
      tags:
      - Manifests
      summary: Manifest eligible orders
      description: 'Manifest all orders in ''Label Generated'' and ''Despatched'' statuses and return manifest paperwork where possible.

        '
      operationId: ManifestEligibleAsync
      parameters:
      - name: request
        in: body
        required: false
        schema:
          $ref: '#/definitions/ManifestEligibleOrdersRequest'
      responses:
        '201':
          description: The Manifest all eligible orders request was successful.
          schema:
            $ref: '#/definitions/ManifestOrdersResponse'
        '202':
          description: The Manifest eligible orders request was successful but PDF is not yet available.
          schema:
            $ref: '#/definitions/ManifestOrdersResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ManifestErrorsResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (Feature not available)
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ManifestErrorsResponse'
      security:
      - Bearer: []
  /manifests/retry/{manifestIdentifier}:
    post:
      tags:
      - Manifests
      summary: Retry manifest
      description: Retry a manifest operation if the eligible orders were not able to be successfully processed.
      operationId: RetryManifestAsync
      parameters:
      - $ref: '#/parameters/manifestIdentifier'
      responses:
        '201':
          description: The Retry Manifest request was successful.
          schema:
            $ref: '#/definitions/ManifestOrdersResponse'
        '202':
          description: The retry request was successfully processed but documentation is not yet available.
          schema:
            $ref: '#/definitions/ManifestOrdersResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ManifestErrorsResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (Feature not available)
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ManifestErrorsResponse'
      security:
      - Bearer: []
  /manifests/{manifestIdentifier}:
    get:
      tags:
      - Manifests
      summary: Get manifest
      description: Retrieve manifest paperwork for a previously successful manifest eligible orders call.
      operationId: GetManifestAsync
      parameters:
      - $ref: '#/parameters/manifestIdentifier'
      responses:
        '200':
          description: The Get Manifest request was successfully processed.
          schema:
            $ref: '#/definitions/ManifestDetailsResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ManifestErrorsResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (Feature not available)
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ManifestErrorsResponse'
      security:
      - Bearer: []
definitions:
  ManifestDetailsResponse:
    type: object
    required:
    - manifestNumber
    properties:
      manifestNumber:
        type: number
      status:
        type: string
        enum:
        - In Progress
        - Completed
        - Failed
      documentPdf:
        type: string
        description: manifest in format base64 string
  ManifestEligibleOrdersRequest:
    type: object
    properties:
      carrierName:
        type: string
        description: The name of the carrier to manifest orders for.
  ManifestErrorsErrorDetailsResponse:
    type: object
    properties:
      code:
        type: string
      description:
        type: string
  ManifestOrdersResponse:
    type: object
    required:
    - manifestNumber
    properties:
      manifestNumber:
        type: number
      documentPdf:
        type: string
        description: manifest in format base64 string
  ManifestErrorsResponse:
    type: object
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/ManifestErrorsErrorDetailsResponse'
parameters:
  manifestIdentifier:
    in: path
    name: manifestIdentifier
    required: true
    type: integer
    description: The manifest number returned from the initial manifest eligible orders endpoint call
securityDefinitions:
  Bearer:
    type: apiKey
    description: Authorization header using the Bearer scheme. Enter 'Bearer [space] and then your token.
    name: Authorization
    in: header
